### ISSUE TITLE
parse thrift into markdown or something

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-api#21]
our most authoritative description of fields and nuance is the thrift. Is there some way we can parse it into markdown or something so that there's a human readable copy on zipkin.io?

ex.
https://github.com/openzipkin/zipkin-api/blob/master/thrift/zipkinCore.thrift#L272

cc @abesto @basvanbeek

**Comment by adriancole** [comment]
offline chat with @basvanbeek maybe we can compile to java, then java to markdown

https://delight-im.github.io/Javadoc-to-Markdown/

**Comment by abesto** [comment]
Or maybe even write a Thrift-Markdown compiler!

**Comment by abesto** [comment]
Soo... this is somewhat embarrassing, but it turns out Thrift has (and has, for pretty much forever had) an HTML generator. Just opened a PR in `openzipkin.github.io` using it.

**Comment by abesto** [comment]
Closing as fixed with https://github.com/openzipkin/openzipkin.github.io/pull/98, reopen if I missed something.
