### ISSUE TITLE
formatting issue in swagger doc

### ISSUE THREAD

**Issue by lducharme** [openzipkin/zipkin-api#40]
Hi, I think there might be a small formatting error in you swagger docs-

For the parameter [lookback](https://github.com/openzipkin/zipkin-api/blob/master/zipkin-api.yaml#L134-L135), I think the expression is supposed to be surrounded with ticks, as in [line 180](https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml). The way this line is now is somewhat difficult to understand in the [get traces docs.](https://zipkin.io/zipkin-api/#/default/get_traces)

Thanks!

**Comment by adriancole** [comment]
nice catch. thanks!
