### ISSUE TITLE
Publish a jar for zipkin-api to maven

### ISSUE THREAD

**Issue by gneokleo** [openzipkin/zipkin-api#45]
The old thrift spec used to be published on zipkin [here](https://mvnrepository.com/artifact/io.zipkin/zipkin-thrift). Would it be possible to publish this as well? We use it to compile it and generate the java code.

**Comment by adriancole** [comment]
hmm.. not sure we want to encourage new use of thrift

**Comment by gneokleo** [comment]
I see. What would be the preferred binary serialization in v2 with cross language support?

**Comment by adriancole** [comment]
proto3, just we've had no end users asking about this recently, so haven't
put forward the effort. There is some core infra in, so it isn't terribly
difficult.

wanna formally request it? https://github.com/openzipkin/zipkin/issues/new

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-api/pull/47 for work in progress

**Comment by adriancole** [comment]
as "zipkin-api" especially in maven could be confused with a potentially future java interface, I think zipkin-proto3 makes more sense. Will set this up

**Comment by adriancole** [comment]
io.zipkin.proto3:zipkin-proto3 is waiting some process clearing from bintray, which will temporarily delay this to maven central. will ping back
