### ISSUE TITLE
Merge master to gh-pages in TravisCI on build success 

### ISSUE THREAD

**Issue by mohsen1** [openzipkin/zipkin-api#5]
Right now, we have to manually merge changes in master to `gh-pages` branch to keep it updated with master. TravisCI has this feature to do stuff on build success. I've never done it before but it should be possible.

**Comment by adriancole** [comment]
just now synced

**Comment by adriancole** [comment]
just now synced

**Comment by adriancole** [comment]
just now synced

**Comment by jcchavezs** [comment]
This is fixed now: https://github.com/openzipkin/zipkin-api/pull/83

**Comment by adriancole** [comment]
Verified. @openzipkin/core please thank @jcchavezs as now our api shows all, including the new /traceMany endpoint! https://zipkin.io/zipkin-api/#/
